name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: pip3 install -r ./requirements.txt
    - name: cmake version
      run: cmake --version
    - name: create buildfolder
      run: mkdir build
    - name: run cmake
      run: cmake -S . -B build
    - name: build 
      run: cmake --build build
    - name: run application
      run: ./build/bin/hello
